### ISSUE TITLE
Not compatible with extension version 2.0

### ISSUE THREAD

**Issue by aemaem** [safaariman/ulauncher-jira#1]
The extension is not compatible with the current extension version 2.0 (http://docs.ulauncher.io/en/latest/extensions/migration.html#migrate-from-api-v1-to-v2-0-0).
![image](https://user-images.githubusercontent.com/7202266/60756339-9f9dba80-9ffc-11e9-9a99-69f4fe5b8dbe.png)

**Comment by safaariman** [comment]
Thanks for reporting. I will check and fix it as soon as possible.

**Comment by safaariman** [comment]
Jira extension is compatible with the latest version of Ulauncher. Feel free to open new issue if you have any problem. :)
